Implementation of invalid user input exception
chrisr-diffblue/cbmc pull request #5
Opened 2018-07-02 12:36 UTC by NlightNFotis

This PR contains an implementation of an erroneous user input exception, and changes the unstructured `throw 0`s in the `cbmc/` folder into structured exceptions and preconditions/invariants.

2018-07-02 14:04 UTC, hannes-steffenhagen-diffblue approved these changes
LGTM for the most part

2018-07-02 14:04 UTC, hannes-steffenhagen-diffblue commented on src/cbmc/cbmc_solvers.cpp
> +      "");
This is quite a big improvement over the previous version that didn't tell you what option it didn't like, :+1:

2018-07-02 14:04 UTC, hannes-steffenhagen-diffblue commented on src/util/exception_utils.h
> +    res += reason;
I think it's fine to have the `"Reason: "` part here, I just didn't like forcing the form of the part after the reason.
Sorry for being unclear with this

2018-07-03 12:12 UTC, danpoe requested changes

2018-07-03 12:12 UTC, danpoe commented on src/cbmc/bv_cbmc.cpp
> +  PRECONDITION(expr.operands().size() != 4);
We could use `DATA_INVARIANT` here which is for checking whether goto programs, exprts, etc. are well-formed. Then we can also keep the error message.

2018-07-03 12:12 UTC, danpoe commented on src/cbmc/show_vcc.cpp
> +        "Failed to open suggested file", "--outfile", "");
We can drop "suggested", and append the filename to the first argument.

2018-07-03 12:12 UTC, danpoe commented on src/util/exception_utils.h
> +    std::string correct_input)
Can we have an empty string default argument for `correct_input`?

2018-07-03 12:12 UTC, danpoe commented on src/util/exception_utils.h
> +    correct_input.empty() ? "\n" : res += " Try: " + correct_input + "\n";
I think we need to add a newline before `" Try"`.

2018-07-03 12:12 UTC, danpoe commented on src/cbmc/cbmc_main.cpp
> +  catch(invalid_user_input_exceptiont &e)
Currently if an exception is caught here the program still exits with a zero exit code. We should change this to exit with an error code.

I think we can also move the exception catching code to `parse_options_baset::main()` (wrapping the call to `doit()`). Then the tools that inherit from it don't need to repeat the exception handlers.

2018-07-03 14:33 UTC, NlightNFotis commented on src/util/exception_utils.h
> +    correct_input.empty() ? "\n" : res += " Try: " + correct_input + "\n";
I'd rather it be kept on the same line.

2018-07-03 14:35 UTC, NlightNFotis commented on src/cbmc/bv_cbmc.cpp
> +  PRECONDITION(expr.operands().size() != 4);
I won't implement this. It's easily implementable, but the error message is just redundant IMO. It doesn't convey any information that the precondition expression doesn't convey already.

2018-07-03 14:37 UTC, NlightNFotis commented on src/cbmc/cbmc_main.cpp
> +  catch(invalid_user_input_exceptiont &e)
This is very interesting. It's a great suggestion, but this needs a little bit thinking about how to properly implement this (I haven't thought it through yet, might be easier than I realise)

2018-07-03 14:58 UTC, danpoe commented on src/cbmc/bv_cbmc.cpp
> +  PRECONDITION(expr.operands().size() != 4);
Hm the error message had the additional information that `expr` is a waitfor expression (i.e., `expr.id()` is `"waitfor"`). From the condition we only see that it is some expression with four operands.

2018-07-03 15:00 UTC, NlightNFotis commented on src/cbmc/bv_cbmc.cpp
> +  PRECONDITION(expr.operands().size() != 4);
Good spot, didn't notice that. I guess I can rewrite that a little bit as well.

2018-07-03 15:00 UTC, danpoe commented on src/util/exception_utils.h
> +    correct_input.empty() ? "\n" : res += " Try: " + correct_input + "\n";
Should we add a separator character then? Maybe a comma.

2018-07-03 15:43 UTC, NlightNFotis commented
@hannes-steffenhagen-diffblue @danpoe Can I request a new review from both of you? Made some substantial changes on where we handle exceptions in the latest commit.

2018-07-04 15:04 UTC, danpoe commented on src/cbmc/cbmc_main.cpp
> +#include <util/exception_utils.h>
I think those two includes are now not needed anymore

2018-07-04 15:05 UTC, danpoe commented on src/cbmc/show_vcc.cpp
> +        "Failed to open file" + filename, "--outfile");
`... file"` -> `...file "`

2018-07-04 15:17 UTC, danpoe approved these changes
Looks good to me!

2018-07-04 15:21 UTC, hannes-steffenhagen-diffblue commented on src/cbmc/show_vcc.cpp
> +        "Failed to open file: " + filename, "--outfile");
Thinking about it, I don't really like this being an invalid user input exception (I suppose you can justify it being subject to user input as they control the filename, but technically whether or not we're able to open the file isn't necessarily up to the user).

Not a blocker for sure, but in general I'd have a preference for IO related exceptions to have their own place.

2018-07-04 15:21 UTC, hannes-steffenhagen-diffblue approved these changes
Still looks OK to me

2018-07-17 10:21 UTC, chrisr-diffblue approved these changes

2018-07-17 10:21 UTC, merged